---
title: "Quiz"
author: "Hazrul"
date: "23 February 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Quiz Week 5

Q1.

```{r}
library(arm)
library(ggplot2)
library(car)
library(gridExtra)
nursery_df <- read.table("NurserySchools.txt", header = TRUE)
head(nursery_df, 5)
summary(nursery_df)
```



```{r}
pairs(nursery_df[,-1])

```



```{r}
with(nursery_df, cor(Dep, NurseryExp))
with(nursery_df, cor(NurseryProv,NurseryExp))
```


```{r}

p1 <- ggplot(data = nursery_df, aes(x=Dep, y= NurseryExp)) + geom_point() + geom_smooth(method = "lm")
p2 <- ggplot(data = nursery_df, aes(x=NurseryProv , y= NurseryExp)) + geom_point() + geom_smooth(method = "lm")

grid.arrange(p1,p2,nrow=1)
```

```{r}
out1 <- which(nursery_df$NurseryExp==max(nursery_df$NurseryExp))
 
first_lm <- lm(NurseryExp ~ Dep + NurseryProv , data = nursery_df)

display(first_lm)

```


```{r}
newdf_nursery <- nursery_df[-out1,]

imp_first <- lm(NurseryExp ~ Dep + NurseryProv , data = newdf_nursery)
display(imp_first)

```


```{r}
show_outliers<- function(the.linear.model,topN){
#length of data
n=length(fitted(the.linear.model))
#number of parameters estimated
p=length(coef(the.linear.model))
#standardised residuals over 3
res.out<-which(abs(rstandard(the.linear.model))>3) #sometimes >2
#topN values
res.top<-head(rev(sort(abs(rstandard(the.linear.model)))),topN)
#high leverage values
lev.out<-which(lm.influence(the.linear.model)$hat>2*p/n)
#topN values
lev.top<-head(rev(sort(lm.influence(the.linear.model)$hat)),topN)
#high diffits
dffits.out<-which(dffits(the.linear.model)>2*sqrt(p/n))
#topN values
dffits.top<-head(rev(sort(dffits(the.linear.model))),topN)
#Cook's over 1
cooks.out<-which(cooks.distance(the.linear.model)>1)
#topN cooks
cooks.top<-head(rev(sort(cooks.distance(the.linear.model))),topN)
#Create a list with the statistics -- cant do a data frame as different lengths 
list.of.stats<-list(Std.res=res.out,Std.res.top=res.top, Leverage=lev.out, Leverage.top=lev.top, DFFITS=dffits.out, DFFITS.top=dffits.top, Cooks=cooks.out,Cooks.top=cooks.top)
#return the statistics
list.of.stats }

show_outliers(first_lm, 5)


```



```{r}
nursery_df[c(18,28), 2:4]
```


```{r}

```


```{r}

```


```{r}

```














































